name: user_profile_avatar
description: A simple widget that display round profile picture and display native circular progress indicator whilst image is being fetched.
homepage: https://github.com/zeshanghayoomi/flutter_user_profile_avatar
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  provider: ^6.0.1
  flutter:
    sdk: flutter
  image_picker:
  cached_network_image: ^3.0.0
  image_cropper: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/user_profile_avatar/src/local_assets/icons/user_empty_avatar.png

